# Generated by Django 5.1.4 on 2024-12-23 14:33

import app.utils.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("promotional_channel", models.CharField(max_length=200, null=True)),
                ("budget", models.DecimalField(decimal_places=1, max_digits=20)),
            ],
            options={
                "verbose_name": "ad company",
                "verbose_name_plural": "ad companies",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=10000, null=True)),
                ("price", models.DecimalField(decimal_places=1, max_digits=20)),
            ],
            options={
                "verbose_name": "service",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.PositiveBigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "ad_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.adcompany"
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "document",
                    models.FileField(
                        null=True, upload_to=app.utils.uploads.upload_document
                    ),
                ),
                ("conclusion_date", models.DateField(null=True)),
                ("days_of_action", models.PositiveIntegerField(null=True)),
                ("price", models.DecimalField(decimal_places=1, max_digits=20)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.client"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.service"
                    ),
                ),
            ],
            options={
                "verbose_name": "contract",
            },
        ),
        migrations.AddField(
            model_name="adcompany",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.service"
            ),
        ),
    ]
