# Generated by Django 5.1.4 on 2024-12-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=10000, null=True)),
                ("price", models.DecimalField(decimal_places=1, max_digits=20)),
            ],
            options={
                "verbose_name": "service",
            },
        ),
    ]
