# Generated by Django 5.1.4 on 2024-12-19 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("promotional_channel", models.CharField(max_length=200, null=True)),
                ("budget", models.DecimalField(decimal_places=1, max_digits=20)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.service"
                    ),
                ),
            ],
            options={
                "verbose_name": "ad company",
                "verbose_name_plural": "ad companies",
            },
        ),
    ]
