# Generated by Django 5.1.4 on 2024-12-19 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.PositiveBigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "ad_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.adcompany"
                    ),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="app.contract"
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
            },
        ),
    ]
