# Generated by Django 5.1.4 on 2024-12-28 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_client_ad_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract",
                to="app.client",
            ),
        ),
    ]
